CREATE DATABASE ToDoAppDb

GO
USE ToDoAppDb
CREATE TABLE Categories
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL
)

CREATE TABLE Todos
(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	CategoryId INT NOT NULL FOREIGN KEY REFERENCES Categories (Id) ON DELETE CASCADE,
	Title NVARCHAR(200) NOT NULL,
	IsDone BIT
)

GO
INSERT INTO Categories (Name)
VALUES ('Misc')

